import Head from 'next/head';
import axios from 'axios';
import { GetStaticProps, GetStaticPaths } from 'next';
import Nav from '../../components/Nav';
import { useRouter } from 'next/router';

const linkUrl = [
  {
    name: 'home',
    link: '/'
  },
  {
    name: '01',
    link: '/ssg/1'
  },
  {
    name: '02',
    link: '/ssg/2'
  },
  {
    name: '03',
    link: '/ssg/3'
  },
  {
    name: '04',
    link: '/ssg/4'
  }
];

const getData = async (id: number) => {
  const { data } = await axios.get(`https://swapi.dev/api/people/${id}`);
  return data;
};

export const getStaticPaths = () => {
  // 可以用 axios 先去預抓 data 資料內的 id
  // const paths = data.map(item => {
  //   return params: {id: item.id.toString()}
  // })

  return {
    paths: [{ params: { id: '1' } }, { params: { id: '2' } }, { params: { id: '3' } }],

    /*
      false: 找不到指定id則導向404, 
      true: 直接往下執行, 有 router.isFallback 可使用, 
      blocking: 跟true一樣往下執行, 但沒有 router.isFallback使用
    */

    // fallback: true
    fallback: false
    // fallback: 'blocking'
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const id = Number(params && params.id);
  let data = null;

  try {
    data = await getData(id);
  } catch (err) {
    return {
      notFound: true
    };
  }

  return {
    props: {
      data
    }
  };
};

export default function Home({ data }: any) {
  const router = useRouter();

  //
  if (router.isFallback) {
    return <h1>Loading...</h1>;
  }

  return (
    <>
      <div className=''>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main>
          <h2>Next SSG</h2>
          <Nav linkUrl={linkUrl} />
          <div className='data'>
            <p>name: {data.name}</p>
            <p>url: {data.url}</p>
          </div>
          <p>{JSON.stringify(data)}</p>
        </main>
      </div>

      <style jsx>{`
        .data {
          padding: 1rem 0;
        }

        main {
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          width: 100%;
          height: 100vh;
        }
      `}</style>
    </>
  );
}
