import Head from 'next/head';
import axios from 'axios';
import { GetServerSideProps } from 'next';

const getData = async () => {
  const { data } = await axios.get('https://swapi.dev/api/');
  return data;
};

export const getServerSideProps: GetServerSideProps = async () => {
  const data = await getData();

  return {
    props: {
      data
    }
  };
};

export default function Home({ data }: any) {
  console.log(data);
  return (
    <>
      <div className=''>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main>
          <h2>Next SSR</h2>
          <p>{JSON.stringify(data)}</p>
        </main>
      </div>

      <style jsx>{`
        main {
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          width: 100%;
          height: 100vh;
        }
      `}</style>
    </>
  );
}
