import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <header>
          <Link href='/hookUseTransitionPush'>useTransition</Link>
          <Link href='/hookUseDefferedValue'>useDefferedValue</Link>
          <Link href='/hookUseId'>useId</Link>
        </header>
      </main>
    </div>
  );
}
