import Head from 'next/head';
import axios from 'axios';
import { GetStaticProps, GetStaticPaths } from 'next';
import Nav from '../../components/Nav';
import { useRouter } from 'next/router';

const linkUrl = [
  {
    name: 'home',
    link: '/'
  },
  {
    name: 'all',
    link: '/isr'
  },
  {
    name: '01',
    link: '/isr/1'
  },
  {
    name: '02',
    link: '/isr/2'
  },
  {
    name: '03',
    link: '/isr/3'
  },
  {
    name: '04',
    link: '/isr/4'
  },
  {
    name: '05',
    link: '/isr/5'
  }
];

export const getStaticPaths = async () => {
  const { data } = await axios.get('http://localhost:4000/products');

  const paths = data.map((item: any) => ({
    params: { id: item.id.toString() }
  }));
  console.log(paths);

  return {
    paths,
    // fallback: true
    fallback: false
    // fallback: 'blocking'
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const id = Number(params && params.id);
  const { data } = await axios.get(`http://localhost:4000/products/${id}`);

  return {
    props: {
      data
    },
    revalidate: 10
  };
};

export default function Home({ data }: any) {
  const router = useRouter();

  // fallback true 使用
  if (router.isFallback) {
    return <h1>Loading...</h1>;
  }

  return (
    <>
      <div className=''>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main>
          <h2>Next SSG ID</h2>
          <Nav linkUrl={linkUrl} />
          <div className='data'>
            <p>id: {data.id}</p>
            <p>name: {data.name}</p>
          </div>
          <p>{JSON.stringify(data)}</p>
        </main>
      </div>

      <style jsx>{`
        .data {
          padding: 1rem 0;
        }

        main {
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          width: 100%;
          height: 100vh;
        }
      `}</style>
    </>
  );
}
