import Head from 'next/head';
import axios from 'axios';
import { GetStaticProps, GetStaticPaths } from 'next';
import Nav from '../../components/Nav';
import { useRouter } from 'next/router';

const linkUrl = [
  {
    name: 'home',
    link: '/'
  },
  {
    name: 'all',
    link: '/isr'
  },
  {
    name: '01',
    link: '/isr/1'
  },
  {
    name: '02',
    link: '/isr/2'
  },
  {
    name: '03',
    link: '/isr/3'
  },
  {
    name: '04',
    link: '/isr/4'
  }
];

export const getStaticProps: GetStaticProps = async () => {
  const { data } = await axios.get('http://localhost:4000/products');
  console.log(data);

  return {
    props: {
      data
    },
    revalidate: 10
  };
};

export default function Home({ data }: any) {
  const router = useRouter();

  // fallback true 使用
  if (router.isFallback) {
    return <h1>Loading...</h1>;
  }

  return (
    <>
      <div className=''>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main>
          <h2>Next ISR ID</h2>
          <Nav linkUrl={linkUrl} />
          <div className='data'>
            <p>{JSON.stringify(data)}</p>
          </div>
        </main>
      </div>

      <style jsx>{`
        .data {
          padding: 1rem 0;
        }

        main {
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          width: 100%;
          height: 100vh;
        }
      `}</style>
    </>
  );
}
